server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
#  session:
#    redis:
#      namespace: spring:session
#    store-type: redis
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: aaaa
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://sb2.cdmkygage9u5.ap-northeast-2.rds.amazonaws.com:3306/publicdb?characterEncoding=utf8
   #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://127.0.0.1:3306/shopdb?characterEncoding=utf8
    username: ENC(fGIHFnBehqbzi4DDRRE5yA==)
    password: ENC(qF1qCuCQEp/b2NzFzUX2oQ==)

mybatis:
  type-aliases-package: com.hana.data.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info

app:
  key:
    psKey: ENC(9stHTg5o2wiRj5+q7PSJlq96y7mCUWybdxtM0QC9SkuVMXBvbhyXjg==)
    kakaoKey: ENC(oafLF1dlQJ9jj4wo4T4myOqUx0xyGOk4A4/k02yc8JEKqfMJPjrICRXOZMnGG9Ow)
    kakaoApiKey: ENC(WvOFQwlEvv5FDU/beqhOivSH+033Pkxr5xT+M0uwVIy+J9z/f18ZbLtFMrQ+EFb5)
    whkey: ENC(BcBf+XEhqKXwC3pP2Z5Uui/JZce+Ebfpb9pVJyTUdat1uUwkCSJZ4qrrlH5T67Es)
